### ISSUE TITLE
`check_expires=True` produces an error

### ISSUE THREAD

**Issue by diesieben07** [altcha-org/altcha-lib-py#1]
`extract_params` uses `urllib.parse.parse_qs`, which will return a _list_ for every parameter:
```python
qs = urllib.parse.parse_qs('foo=bar')
# qs = { 'foo': ['bar'] }
```

`extract_params(payload).get('expires')` is then fed into `int()`, which obviously throws, because you cannot convert a list to an int.

**Comment by ovx** [comment]
Thank you for fixing it, published as 0.1.4.
